# This is an example config file for review-branch. You can use it as a
# starting point by copying it into the top level of your repository as
# `review-branch-config.yaml`.

# This is a maximal config. All of the fields below are optional.

# Used to populate the Description field of your review. If you include the
# string "{git_description}" here, it will be replaced with:
#   From commit message:
#   [message from your most recent commit]
description: |
    {git_description}

# Used to populate the Testing Done field of your review.
testing_done: |
    How I know this change works:

# If true, review-branch will push your changes to a new branch named according
# to the config provided by `review_board_branch` below. This can be useful
# if you want to mess with your branch but would like other members of your
# team to be able to check out the code exactly as it was posted for review.
create_new_branch_for_review_board: true

# Settings used to construct the new branch name for your code review. The
# format for this name is:
#
#   {prefix}{separator}{username}{separator}{branch name}
#
# So if your username is "arothman" and your branch is "my_cool_branch", and
# you use the settings below, your review branch would be named
# "reviewboard_arothman_my_cool_branch".
review_board_branch:
    prefix: reviewboard
    separator: /

default_reviewers:
    - diego
